// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt4gYP8fr7u_z4Hi9ODqU3OHrx64ZBwZs',
    appId: '1:151716780030:web:1adda26f1dd8c179fd52af',
    messagingSenderId: '151716780030',
    projectId: 'dailyfood-3f591',
    authDomain: 'dailyfood-3f591.firebaseapp.com',
    storageBucket: 'dailyfood-3f591.firebasestorage.app',
    measurementId: 'G-350YZK1C4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUrl5M5xAVgo6JX_66w97B68_44YKSzw',
    appId: '1:151716780030:android:497841dc77b31be7fd52af',
    messagingSenderId: '151716780030',
    projectId: 'dailyfood-3f591',
    storageBucket: 'dailyfood-3f591.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5TlrdE01X7WNtqvmlQDLpo9FnHDqyRu4',
    appId: '1:151716780030:ios:cd174c6577268016fd52af',
    messagingSenderId: '151716780030',
    projectId: 'dailyfood-3f591',
    storageBucket: 'dailyfood-3f591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5TlrdE01X7WNtqvmlQDLpo9FnHDqyRu4',
    appId: '1:151716780030:ios:cd174c6577268016fd52af',
    messagingSenderId: '151716780030',
    projectId: 'dailyfood-3f591',
    storageBucket: 'dailyfood-3f591.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt4gYP8fr7u_z4Hi9ODqU3OHrx64ZBwZs',
    appId: '1:151716780030:web:1adda26f1dd8c179fd52af',
    messagingSenderId: '151716780030',
    projectId: 'dailyfood-3f591',
    authDomain: 'dailyfood-3f591.firebaseapp.com',
    storageBucket: 'dailyfood-3f591.firebasestorage.app',
    measurementId: 'G-350YZK1C4V',
  );

}